#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Generates and copy to the clipboard a UUID
#?? 1.0.0
##?
##? Usage:
##?   uuid
docs::parse "$@"

uuid=$(uuidgen | tr '[:upper:]' '[:lower:]')
echo -n $uuid | pbcopy
echo $uuid
