#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Open Docline project with PhpStorm
##?
##? Usage:
##?    open_docline_project
docs::parse "$@"

ls ~/code/docline | rofi -show -dmenu -i | xargs -I_ phpstorm ~/code/docline/_ &>/dev/null &
