#!/bin/bash

google-chrome --new-window "docline.atlassian.net/secure/RapidBoard.jspa?projectKey=DOCLINE&rapidView=4" && \
  xdotool key super+Shift+Right && \
  sleep 1 && \
  xdotool key super+Left

google-chrome --new-window $QA_REVIEW_MEET_URL && \
  xdotool key super+Shift+Right && \
  sleep 1 && \
  xdotool key super+Right
