#!/usr/bin/env bash

set -o pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Clone a GitHub repository
##?
##? Usage:
##?    clone_repository
docs::parse "$@"

if [ -z "$GITHUB_TOKEN" ]; then
  echo "You need to setup a GITHUB_TOKEN export"

  exit 2
fi

repo_url=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/user/repos?per_page=200" | jq --raw-output ".[].ssh_url" | fzf)

git clone "$repo_url"

echo "$repo_url"
