#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Change Gnome Terminal theme
##?
##? Usage:
##?    gnome-terminal-theme
docs::parse "$@"

dconfdir=/org/gnome/terminal/legacy/profiles:
profile_id=3543c998-518f-4527-accf-5df7c0027ecd
profile_name="Codely"

dconf write $dconfdir/list "['$profile_id']"
dconf write $dconfdir/default "'$profile_id'"
dconf write $dconfdir/:$profile_id/visible-name "'$profile_name'"

# Text
dconf write $dconfdir/:$profile_id/use-system-font false
dconf write $dconfdir/:$profile_id/font "'Monospace 14'"

# Cursor
dconf write $dconfdir/:$profile_id/cursor-shape "'ibeam'"
dconf write $dconfdir/:$profile_id/cursor-blink-mode "'off'"

# Colors
dconf write $dconfdir/:$profile_id/use-theme-colors false
dconf write $dconfdir/:$profile_id/foreground-color "'#EBDBB2'"
dconf write $dconfdir/:$profile_id/background-color "'#282828'"
dconf write $dconfdir/:$profile_id/bold-color "'#FEFFFF'"
dconf write $dconfdir/:$profile_id/bold-color-same-as-fg false
dconf write $dconfdir/:$profile_id/palette "['#282828', '#F67667', '#B8BB26', '#FABD2F', '#84A498', '#D3859A', '#8EC07B', '#EBDBB2', '#928373', '#F28E82', '#B2B437', '#F1BF4A', '#95A19D', '#CD98A6', '#9EBD93', '#E5DDC7']"

# Command
dconf write $dconfdir/:$profile_id/use-custom-command true
dconf write $dconfdir/:$profile_id/custom-command "'/bin/zsh'"
